#! /bin/bash
# generated by generate_submodules_add_script.sh

pushd $(dirname $0)                                                                                     2> /dev/null   > /dev/null
cd ..


mode="R"

Win7DEV_BASEDIR=/media/sf_D_DRIVE/h/prj/1original/visyond/visyond

function git_submod_add {
    git submodule  add $1 $2
    if test "$mode" = "W" ; then
        git_register_remote_for_UnixVM $1 $2
    fi
}

function git_register_remote_for_UnixVM {
    if test -d "$2" ; then
        if test -d "$Win7DEV_BASEDIR/$2" ; then
            pushd $2                                                                                    2> /dev/null  > /dev/null
            git remote remove Win7DEV
            git remote add Win7DEV $Win7DEV_BASEDIR/$2
            popd                                                                                        2> /dev/null  > /dev/null
        fi
    fi
}

getopts ":Wh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
W )
  echo "--- registering Win7DEV as remote ---"
  mode="W"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  if test -d "$1" ; then
    Win7DEV_BASEDIR=$1
  fi
  #
  # register Win7DEV remote for main repo as well!
  if test -d "$Win7DEV_BASEDIR" ; then
    git remote remove Win7DEV
    git remote add Win7DEV $Win7DEV_BASEDIR
  fi
  ;;

"?" )
  echo "--- registering git submodules ---"
  mode="R"
  ;;

* )
  cat <<EOT
$0 [-W <optional_remote_path>]

set up git submodules / submodule references for all submodules.

-W       : set up 'Win7DEV' remote reference per submodule

           When you don't specify the remote path yourself,
           the default is set to:
             "$Win7DEV_BASEDIR"

EOT
  exit
  ;;
esac




git_submod_add   git@github.com:GerHobbelt/bespoke-advanced.git                          plugins/advanced
git_submod_add   git@github.com:GerHobbelt/bespoke-backdrop.git                          plugins/backdrop
git_submod_add   git@github.com:GerHobbelt/bespoke-blackout.git                          plugins/blackout
git_submod_add   git@github.com:GerHobbelt/bespoke-bullets.git                           plugins/bullets
git_submod_add   git@github.com:GerHobbelt/bespoke-classes.git                           plugins/classes
git_submod_add   git@github.com:GerHobbelt/bespoke-cursor.git                            plugins/cursor
git_submod_add   git@github.com:GerHobbelt/bespoke-forms.git                             plugins/forms
git_submod_add   git@github.com:GerHobbelt/bespoke-fullscreen.git                        plugins/fullscreen
git_submod_add   git@github.com:GerHobbelt/bespoke-fx.git                                plugins/fx
git_submod_add   git@github.com:GerHobbelt/bespoke-hash.git                              plugins/hash
git_submod_add   git@github.com:GerHobbelt/bespoke-hide.git                              plugins/hide
git_submod_add   git@github.com:GerHobbelt/bespoke-history.git                           plugins/history
git_submod_add   git@github.com:GerHobbelt/bespoke-keys.git                              plugins/keys
git_submod_add   git@github.com:GerHobbelt/bespoke-loop.git                              plugins/loop
git_submod_add   git@github.com:GerHobbelt/bespoke-markdown.git                          plugins/markdown
git_submod_add   git@github.com:GerHobbelt/bespoke-math.git                              plugins/math
git_submod_add   git@github.com:GerHobbelt/bespoke-multimedia.git                        plugins/multimedia
git_submod_add   git@github.com:GerHobbelt/bespoke-notes.git                             plugins/notes
git_submod_add   git@github.com:GerHobbelt/bespoke-overview.git                          plugins/overview
git_submod_add   git@github.com:GerHobbelt/bespoke-progress.git                          plugins/progress
git_submod_add   git@github.com:GerHobbelt/bespoke-qrcode.git                            plugins/qrcode
git_submod_add   git@github.com:GerHobbelt/bespoke-scale.git                             plugins/scale
git_submod_add   git@github.com:GerHobbelt/bespoke-simple-overview.git                   plugins/simple-overview
git_submod_add   git@github.com:GerHobbelt/bespoke-state.git                             plugins/state
git_submod_add   git@github.com:GerHobbelt/bespoke-substeps.git                          plugins/substeps
git_submod_add   git@github.com:GerHobbelt/bespoke-sync.git                              plugins/sync
git_submod_add   git@github.com:GerHobbelt/bespoke-theme-build-wars.git                  themes/build-wars
git_submod_add   git@github.com:GerHobbelt/bespoke-theme-fancy.git                       themes/fancy
git_submod_add   git@github.com:GerHobbelt/bespoke-title.git                             plugins/title
git_submod_add   git@github.com:GerHobbelt/bespoke-touch.git                             plugins/touch
git_submod_add   git@github.com:GerHobbelt/bespoke-vcr.git                               plugins/vcr



popd                                                                                                    2> /dev/null   > /dev/null

