#! /bin/bash
# generated by collect_git_remote_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"

getopts ":fqh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="f"

  git submodule sync
  git submodule update --init
  git submodule update --init --recursive

  util/git_checkout_submodules_head.sh
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="q"
  ;;

* )
  cat <<EOT
$0 [-f] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. check out the preferred branch for each submodule
           and register all submodule remotes.
-q       : 'quick', i.e. only register all submodule remotes.
submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.

EOT
  exit
  ;;
esac


submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    #echo register_remote [$path] [$name] [$repo] [$argc] [...]

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if test $hit -ne 0 ; then
        if test -d $path && test -s $path/.git ; then
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
                git remote rm $name
            fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote .                                                             andreypopp                               git@github.com:andreypopp/bespoke.js.git                                         $# $@
register_remote .                                                             bespokejs                                git@github.com:bespokejs/bespoke.git                                             $# $@
register_remote .                                                             bespokejs-original                       git@github.com:bespokejs/bespoke.git                                             $# $@
register_remote .                                                             danielhaim1                              git@github.com:danielhaim1/bespoke.js.git                                        $# $@
register_remote .                                                             dickdeng                                 git@github.com:dickdeng/bespoke.js.git                                           $# $@
register_remote .                                                             joaobiriba                               git@github.com:joaobiriba/bespoke.js.git                                         $# $@
register_remote .                                                             johnulist                                git@github.com:johnulist/bespoke.js.git                                          $# $@
register_remote .                                                             latentflip                               git@github.com:latentflip/bespoke.js.git                                         $# $@
register_remote .                                                             malinowska                               git@github.com:malinowska/bespoke.js.git                                         $# $@
register_remote .                                                             manuelcabral                             git@github.com:manuelcabral/bespoke.js.git                                       $# $@
register_remote .                                                             mcollina                                 git@github.com:mcollina/bespoke.js.git                                           $# $@
register_remote .                                                             medikoo                                  git@github.com:medikoo/bespoke.js.git                                            $# $@
register_remote .                                                             modohash                                 git@github.com:modohash/bespoke.js.git                                           $# $@
register_remote .                                                             ndeverge                                 git@github.com:ndeverge/bespoke.js.git                                           $# $@
register_remote .                                                             neochief                                 git@github.com:neochief/bespoke.js.git                                           $# $@
register_remote .                                                             rpocklin                                 git@github.com:rpocklin/bespoke.js.git                                           $# $@
register_remote .                                                             ultimatedelman                           git@github.com:ultimatedelman/bespoke.js.git                                     $# $@
register_remote plugins/advanced                                              joelpurra-original                       git@github.com:joelpurra/bespoke-advanced.git                                    $# $@
register_remote plugins/backdrop                                              bespokejs-original                       git@github.com:bespokejs/bespoke-backdrop.git                                    $# $@
register_remote plugins/blackout                                              opendevise-original                      git@github.com:opendevise/bespoke-blackout.git                                   $# $@
register_remote plugins/bullets                                               bespokejs-original                       git@github.com:bespokejs/bespoke-bullets.git                                     $# $@
register_remote plugins/classes                                               bespokejs-original                       git@github.com:bespokejs/bespoke-classes.git                                     $# $@
register_remote plugins/cursor                                                opendevise-original                      git@github.com:opendevise/bespoke-cursor.git                                     $# $@
register_remote plugins/forms                                                 bespokejs-original                       git@github.com:bespokejs/bespoke-forms.git                                       $# $@
register_remote plugins/fullscreen                                            opendevise-original                      git@github.com:opendevise/bespoke-fullscreen.git                                 $# $@
register_remote plugins/fx                                                    developerworks-original                  git@github.com:developerworks/bespoke-fx.git                                     $# $@
register_remote plugins/fx                                                    sferey                                   git@github.com:sferey/bespoke-fx.git                                             $# $@
register_remote plugins/hash                                                  bespokejs-original                       git@github.com:bespokejs/bespoke-hash.git                                        $# $@
register_remote plugins/hide                                                  aaronpowell-original                     git@github.com:aaronpowell/bespoke-hide.git                                      $# $@
register_remote plugins/history                                               medikoo-original                         git@github.com:medikoo/bespoke-history.git                                       $# $@
register_remote plugins/keys                                                  bespokejs-original                       git@github.com:bespokejs/bespoke-keys.git                                        $# $@
register_remote plugins/keys                                                  opendevise-nav-kbd                       git@github.com:opendevise/bespoke-nav-kbd.git                                    $# $@
register_remote plugins/loop                                                  bespokejs-original                       git@github.com:bespokejs/bespoke-loop.git                                        $# $@
register_remote plugins/markdown                                              aaronpowell                              git@github.com:aaronpowell/bespoke-markdown.git                                  $# $@
register_remote plugins/markdown                                              aaronpowell-original                     git@github.com:aaronpowell/bespoke-markdown.git                                  $# $@
register_remote plugins/markdown                                              davidmarkclements                        git@github.com:davidmarkclements/bespoke-markdown.git                            $# $@
register_remote plugins/markdown                                              fegemo                                   git@github.com:fegemo/bespoke-markdown.git                                       $# $@
register_remote plugins/math                                                  fegemo-original                          git@github.com:fegemo/bespoke-math.git                                           $# $@
register_remote plugins/multimedia                                            opendevise-original                      git@github.com:opendevise/bespoke-multimedia.git                                 $# $@
register_remote plugins/notes                                                 medikoo-original                         git@github.com:medikoo/bespoke-notes.git                                         $# $@
register_remote plugins/overview                                              opendevise-original                      git@github.com:opendevise/bespoke-overview.git                                   $# $@
register_remote plugins/progress                                              bespokejs-original                       git@github.com:bespokejs/bespoke-progress.git                                    $# $@
register_remote plugins/qrcode                                                fegemo-original                          git@github.com:fegemo/bespoke-qrcode.git                                         $# $@
register_remote plugins/scale                                                 bespokejs-original                       git@github.com:bespokejs/bespoke-scale.git                                       $# $@
register_remote plugins/simple-overview                                       fegemo-original                          git@github.com:fegemo/bespoke-simple-overview.git                                $# $@
register_remote plugins/state                                                 bespokejs-original                       git@github.com:bespokejs/bespoke-state.git                                       $# $@
register_remote plugins/substeps                                              alampros                                 git@github.com:alampros/bespoke-substeps.git                                     $# $@
register_remote plugins/substeps                                              medikoo-original                         git@github.com:medikoo/bespoke-substeps.git                                      $# $@
register_remote plugins/sync                                                  medikoo-original                         git@github.com:medikoo/bespoke-sync.git                                          $# $@
register_remote plugins/title                                                 medikoo-original                         git@github.com:medikoo/bespoke-title.git                                         $# $@
register_remote plugins/title                                                 opendevise-original                      git@github.com:opendevise/bespoke-title.git                                      $# $@
register_remote plugins/touch                                                 bespokejs-original                       git@github.com:bespokejs/bespoke-touch.git                                       $# $@
register_remote plugins/touch                                                 opendevise-nav-kbd                       git@github.com:opendevise/bespoke-nav-touch.git                                  $# $@
register_remote plugins/vcr                                                   bespokejs-original                       git@github.com:bespokejs/bespoke-vcr.git                                         $# $@
register_remote themes/build-wars                                             akatopo-original                         git@github.com:akatopo/bespoke-theme-build-wars.git                              $# $@
register_remote themes/fancy                                                  fegemo-original                          git@github.com:fegemo/bespoke-theme-fancy.git                                    $# $@



popd                                                                            2> /dev/null   > /dev/null

